-- Seed all 6 estimator templates into Supabase
-- Run in Supabase Dashboard → SQL Editor

INSERT INTO public.templates (id, tenant_id, name, sort_order, active, template_data)
SELECT 'gaf-hdz', '5249f9c0-9fca-46c8-896c-4e35be437024', 'GAF HDZ Shingles', 1, true, '{"id": "gaf-hdz", "name": "GAF HDZ", "label": "GAF HDZ Shingles", "type": "roof", "timeline": "4 to 6 weeks from final measure", "mainProductId": "gafhz", "description": "GAF HDZ shingles offer a combination of beauty and benefits that go beyond any other GAF shingle. The GAF Warranty is available with the installation of GAF Timberline HDZ Shingles and the addition of 4+ components of the GAF Lifetime Roofing System.\n\nAdvantage size, synthetic underlayment to protect the sheeting. Ice and water shield installed 6 ft from the edge (2 layers) and 3 ft in the valley and all new drip edge.\n\n(2) pieces of wood are included in the job price. If any more need to be replaced, we will document the replacement and an additional charge of $65 per sheet will be added to the balance due.", "warrantyBase": "Lifetime product guarantee on shingles. 10 years manufacturer-backed workmanship coverage.", "warranty": "GAF Master Elite Lifetime Warranty on Labor and Material \u2014 transferable for 50 years prorated to next homeowner.", "colorFields": [{"id": "shingleColor", "label": "Shingle Color", "options": "shingle_gaf"}, {"id": "dripEdgeColor", "label": "Drip Edge Color", "options": "drip_edge", "hint": "White or Brown"}, {"id": "flashingColor", "label": "Flashing Color", "options": "flashing", "hint": "Black or Brown"}], "fixedItems": ["chimney", "pipebo", "nails", "delivery", "permits", "timeline4to6"], "dimItems": {"ridgeLF": "ridge", "eaveLF": ["f9748aee", "leading"], "iceWaterLF": "icewater", "valleyLF": "step", "gutterLF": "gutter5"}, "pitchItems": {"30": "steep1", "40": "steep2"}, "layerItem": "extra"}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.templates WHERE id = 'gaf-hdz');

INSERT INTO public.templates (id, tenant_id, name, sort_order, active, template_data)
SELECT 'iko-cambridge', '5249f9c0-9fca-46c8-896c-4e35be437024', 'IKO Cambridge Shingles', 2, true, '{"id": "iko-cambridge", "name": "IKO Cambridge", "label": "IKO Cambridge Shingles", "type": "roof", "timeline": "4 to 6 weeks from final measure", "mainProductId": "ikocam", "description": "IKO Cambridge laminated architectural roofing shingles \u2014 IKO''s most popular among homeowners and roofing contractors. Available in a wide array of stunning, patented color blends. Cambridge architectural shingles have one of the heaviest mats in the roofing industry for superior weather protection.\n\nAdvantage size, synthetic underlayment to protect the sheeting. Ice and water shield installed 6 ft from the edge (2 layers) and 3 ft in the valley and all new drip edge.\n\n(2) pieces of wood are included in the job price. If any more need to be replaced, an additional charge of $65 per sheet will be added to the balance due.", "warranty": "50 Year Manufacturer Material Warranty and 10 Year Craftsmanship Warranty to original homeowner, transferable pro-rated.", "colorFields": [{"id": "shingleColor", "label": "Shingle Color", "options": "shingle_iko"}, {"id": "dripEdgeColor", "label": "Drip Edge Color", "options": "drip_edge", "hint": "White or Brown"}, {"id": "flashingColor", "label": "Flashing Color", "options": "flashing", "hint": "Black or Brown"}], "fixedItems": ["chimney", "pipebo", "nails", "delivery", "permits", "timeline4to6"], "dimItems": {"ridgeLF": "ridge", "eaveLF": ["f9748aee", "leading"], "iceWaterLF": "icewater", "valleyLF": "step", "gutterLF": "gutter5"}, "pitchItems": {"30": "steep1", "40": "steep2"}, "layerItem": "extra"}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.templates WHERE id = 'iko-cambridge');

INSERT INTO public.templates (id, tenant_id, name, sort_order, active, template_data)
SELECT 'metal', '5249f9c0-9fca-46c8-896c-4e35be437024', 'Metal Roof (R Panel)', 3, true, '{"id": "metal", "name": "Metal R Panel", "label": "Metal Roof (R Panel)", "type": "roof", "timeline": "6 to 8 weeks from final measure", "mainProductId": "17dbb335", "description": "Metal Roof \u2014 R Panel. Fasteners show but will be sealed with stainless steel screws and a sealed Grommet. Metal carries a lifetime warranty and a 10-year no-fade paint warranty.", "warranty": "Lifetime Warranty. 10-year no-fade paint warranty. 25-year transferable pro-rated.", "colorFields": [{"id": "metalColor", "label": "Color Selected", "options": "metal_color"}], "fixedItems": ["chimney", "pipebo", "delivery", "permits", "timeline6to8"], "dimItems": {"valleyLF": "step", "gutterLF": "gutter6"}, "pitchItems": {"30": "steep1", "40": "steep2"}, "layerItem": null}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.templates WHERE id = 'metal');

INSERT INTO public.templates (id, tenant_id, name, sort_order, active, template_data)
SELECT 'ody-housewrap', '5249f9c0-9fca-46c8-896c-4e35be437024', 'Odyssey Plus .044 w/ House Wrap', 10, true, '{"id": "ody-housewrap", "name": "Ody Plus .044 House Wrap", "label": "Odyssey Plus .044 w/ House Wrap", "type": "siding", "timeline": "13 to 17 weeks from final measure", "mainProductId": "odysseywrap", "description": "Odyssey Plus Standard Colors only \u2014 .044 panel thickness with House Wrap. Secure Lock advanced Rollover nail hem for superior rigidity. Extra strong rollover nail hem with double row slot.\n\nPremium Dark colors will only carry the Manufacturer''s Lifetime Warranty. Renew Home Exteriors recommends Charter Oak .046 thickness in premium darker colors.\n\n*Mounting blocks will be in the same color as the siding color chosen.", "warranty": "10-year labor warranty on standard colors only. Lifetime Manufacturer Warranty. *See warranty for complete details.", "colorFields": [{"id": "sidingStyle", "label": "Siding Style", "options": "siding_style", "hint": "DL or Straight Lap"}, {"id": "sidingColor", "label": "Siding Color", "options": "siding_ody"}, {"id": "cornerPostColor", "label": "Corner Post Color", "options": "siding_ody"}, {"id": "soffitColor", "label": "Vinyl Soffit Color", "options": "trim"}, {"id": "faciaColor", "label": "Aluminum Fascia Wrap Color", "options": "trim"}, {"id": "windowCapColor", "label": "Full Window Cap Color", "options": "trim"}, {"id": "doorCapColor", "label": "Entry / Patio Door Cap Color", "options": "trim"}, {"id": "garageDoorCapColor", "label": "Garage Door Cap Color", "options": "trim"}, {"id": "gutterColor", "label": "Gutter Color", "options": "gutter"}], "fixedItems": ["sidfastn", "delivery", "permits", "timeline13to17"], "dimItems": {"sidingCorners": "sidcorn", "fasciaLF": "facia", "soffitSQ": "vinylsoffit", "gutterLF": "gutter5"}, "pitchItems": {}, "layerItem": null}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.templates WHERE id = 'ody-housewrap');

INSERT INTO public.templates (id, tenant_id, name, sort_order, active, template_data)
SELECT 'ody-polar', '5249f9c0-9fca-46c8-896c-4e35be437024', 'Odyssey Plus .044 w/ Polar Board', 11, true, '{"id": "ody-polar", "name": "Ody Plus .044 3/8 Polar Board", "label": "Odyssey Plus .044 w/ 3/8 Polar Board", "type": "siding", "timeline": "13 to 17 weeks from final measure", "mainProductId": "odyssey", "description": "Odyssey Plus Standard Colors only \u2014 .044 panel thickness with 3/8 polar board. Secure Lock advanced Rollover nail hem for superior rigidity. Extra strong rollover nail hem with double row slot.\n\nPremium Dark colors will only carry the Manufacturer''s Lifetime Warranty. Renew Home Exteriors recommends Charter Oak .046 thickness in premium darker colors.\n\n*Mounting blocks will be in the same color as the siding color chosen.", "warranty": "10-year labor warranty on standard colors only. Lifetime Manufacturer Warranty. *See warranty for complete details.", "colorFields": [{"id": "sidingStyle", "label": "Siding Style", "options": "siding_style", "hint": "DL or Straight Lap"}, {"id": "sidingColor", "label": "Siding Color", "options": "siding_ody"}, {"id": "cornerPostColor", "label": "Corner Post Color", "options": "siding_ody"}, {"id": "soffitColor", "label": "Vinyl Soffit Color", "options": "trim"}, {"id": "faciaColor", "label": "Aluminum Fascia Wrap Color", "options": "trim"}, {"id": "windowCapColor", "label": "Full Window Cap Color", "options": "trim"}, {"id": "doorCapColor", "label": "Entry / Patio Door Cap Color", "options": "trim"}, {"id": "garageDoorCapColor", "label": "Garage Door Cap Color", "options": "trim"}, {"id": "gutterColor", "label": "Gutter Color", "options": "gutter"}], "fixedItems": ["sidfastn", "delivery", "permits", "timeline13to17"], "dimItems": {"sidingCorners": "sidcorn", "fasciaLF": "facia", "soffitSQ": "vinylsoffit", "gutterLF": "gutter5"}, "pitchItems": {}, "layerItem": null}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.templates WHERE id = 'ody-polar');

INSERT INTO public.templates (id, tenant_id, name, sort_order, active, template_data)
SELECT 'charter-oak', '5249f9c0-9fca-46c8-896c-4e35be437024', 'Charter Oak Premium .046', 12, true, '{"id": "charter-oak", "name": "Charter Oak .046", "label": "Charter Oak Premium .046", "type": "siding", "timeline": "13 to 17 weeks from final measure", "mainProductId": "590da916", "description": "Charter Oak Premium Siding \u2014 .046 premium panel thickness with 3/8 Insulation polar board. Rollover nail hem gives Charter Oak its superior ability to resist the force of extreme winds. Exclusive Tri Beam design gives Charter Oak superior strength, up to five times more rigid than the competition. Charter Oak siding has been independently tested to withstand Category 5 hurricane-force winds.\n\n*Mounting blocks will be in the same color as the siding.", "warranty": "Lifetime Warranty Parts and Labor. 25-year transferable pro-rated.", "colorFields": [{"id": "sidingStyle", "label": "Siding Style", "options": "siding_style", "hint": "DL or Straight Lap"}, {"id": "sidingColor", "label": "Siding Color", "options": "siding_charter"}, {"id": "cornerPostColor", "label": "Corner Post Color", "options": "siding_charter"}, {"id": "soffitColor", "label": "Vinyl Soffit Color", "options": "trim"}, {"id": "porchSoffitColor", "label": "Porch Solid Vinyl Soffit Color", "options": "trim"}, {"id": "faciaColor", "label": "Aluminum Fascia Wrap Color", "options": "trim"}, {"id": "windowCapColor", "label": "Full Window Cap Color", "options": "trim"}, {"id": "doorCapColor", "label": "Entry / Patio Door Cap Color", "options": "trim"}, {"id": "garageDoorCapColor", "label": "Garage Door Cap Color", "options": "trim"}, {"id": "gutterColor", "label": "Gutter Color", "options": "gutter"}], "fixedItems": ["sidfastn", "delivery", "permits", "timeline13to17"], "dimItems": {"sidingCorners": "sidcorn", "fasciaLF": "facia", "soffitSQ": "vinylsoffit", "gutterLF": "gutter5"}, "pitchItems": {}, "layerItem": null}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.templates WHERE id = 'charter-oak');
